[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "pnpm run dev"
  port = 5173
  # netlify dev will pick up functions from netlify/functions
