[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "pnpm run dev"
  port = 8888
  targetPort = 5173
  framework = "#custom"
  # netlify dev will pick up functions from netlify/functions
